version: 0.1

phases:
  install:
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
      - npm install -f
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  paths:
    - './build/**/*'
    - './appspec.yml'
    - './package.json'
